# Generated by Django 4.1.1 on 2022-11-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="headline",
            field=models.CharField(max_length=150, verbose_name="заголовок"),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="/media/placeholder.png",
                null=True,
                upload_to="images",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="/user.png", null=True, upload_to="images"
            ),
        ),
    ]
